# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/v1/companies.proto for package 'directory.v1'

require 'grpc'
require 'proto/v1/companies_pb'

module Directory
  module V1
    module Companies
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'directory.v1.Companies'

        rpc :GetCompany, ::Directory::V1::GetCompanyReq, ::Directory::V1::Company
      end

      Stub = Service.rpc_stub_class
    end
  end
end
