# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/companies.proto

require 'google/protobuf'


descriptor_data = "\n\x18proto/v1/companies.proto\x12\x0c\x64irectory.v1\"\x1b\n\rGetCompanyReq\x12\n\n\x02id\x18\x01 \x01(\t\"\xbf\x01\n\x07\x43ompany\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x11\n\taddress_1\x18\x03 \x01(\t\x12\x11\n\taddress_2\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x13\n\x0bpostal_code\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65partments\x18\x08 \x03(\t\x12%\n\x07\x66ounder\x18\t \x03(\x0b\x32\x14.directory.v1.Person\"/\n\x06Person\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t2O\n\tCompanies\x12\x42\n\nGetCompany\x12\x1b.directory.v1.GetCompanyReq\x1a\x15.directory.v1.Company\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Directory
  module V1
    GetCompanyReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("directory.v1.GetCompanyReq").msgclass
    Company = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("directory.v1.Company").msgclass
    Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("directory.v1.Person").msgclass
  end
end
